import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

public class Ejercicio3 {
	public static void generateFile(String flName, String str) throws IOException {
		FileWriter writer;
		BufferedWriter writeFilter;
		writer = new FileWriter(flName);
		writeFilter = new BufferedWriter(writer);
		writeFilter.write(str);
		writeFilter.close();
	}
	
	public static void printFile(String flName) throws IOException {
		FileReader reader;
		BufferedReader readerFilter;
		String line;
		reader = new FileReader(flName);
		readerFilter = new BufferedReader(reader);
		
		line = readerFilter.readLine();
		while (line != null) {
			System.out.println(line);
			line = readerFilter.readLine();
		}
		readerFilter.close();
	}
	
	public static int countLines(String flName) throws IOException{ /*me gustaría, en un futuro, meter un binario con flags,
	 												opciones contar{lineas ó caracteres}*/
		FileReader reader;
		BufferedReader readerFilter;
		String line;
		reader = new FileReader(flName);
		readerFilter = new BufferedReader(reader);
		
		line = readerFilter.readLine();
		int count = 0;
		while (line != null) {
			count++;
			line = readerFilter.readLine();
		}
		readerFilter.close();
		return count;
		
	}
	
	
	public static String[] textToArray(String txt) {
		//Retaíla de "replaces" generated by antonIA.
		return txt.replace(",", "")
		           .replace(".", "")
		           .replace("\"", "")
		           .replace("'", "")
		           .replace("“", "")
		           .replace("”", "")
		           .replace("«", "")
		           .replace("»", "")
		           .replace("!", "")
		           .replace("¡", "")
		           .replace("?", "")
		           .replace("¿", "")
		           .replace(":", "")
		           .replace(";", "")
		           .replace("(", "")
		           .replace(")", "")
		           .replace("[", "")
		           .replace("]", "")
		           .replace("{", "")
		           .replace("}", "")
		           .replace("-", "")
		           .replace("_", "")
		           .replace("—", "")
		           .replace("/", "")
		           .replace("\\", "")
		           .replace("*", "")
		           .replace("&", "")
		           .replace("%", "")
		           .replace("$", "")
		           .replace("#", "")
		           .replace("@", "")
		           .replace("~", "")
		           .replace("^", "")
		           .replace("`", "")
		           .replace("+", "")
		           .replace("=", "")
		           .replace("<", "")
		           .replace(">", "")
		           .replace("|", "")
		           .replace("\n", " ")   
		           .replace("\t", " ")   
		           .trim().split(" ");              
	}
	
	public static String extractText(String flName) throws IOException {
		FileReader reader;
		BufferedReader readerFilter;
		reader = new FileReader(flName);
		readerFilter = new BufferedReader(reader);
		String line;
		String txt = "";
		line = readerFilter.readLine();
		while (line != null) { 
			txt += (line+"\n");
			line = readerFilter.readLine();
			}
		readerFilter.close();
		return txt;
		}

	public static void main(String[] args) throws IOException {
		String text;
		int lineCount;
		int charCount;
		
		text = extractText("theVeldt.txt");
		lineCount = countLines("theVeldt.txt");
		
		String[] words = textToArray(text);
		
		charCount = 0;
		for (String word : words) {
			charCount += word.length();
		}
		System.out.println("La cuenta de lineas es: " + lineCount+ "| La cuenta de letras es: "+ charCount +"| La cuenta de palabras es: " + words.length+ "|La longitud promedio de las palabras es: " + ((float)charCount/words.length));
	}

}
